# =======================================================
#
#         Astral Plugins - AstralTags
#            Versão (Patch): v1.0
#            Desenvolvedor: Laas
#
#         Contato (Discord): devlaas
#
# =======================================================

# Informações:

# Antes de tudo é recomendável utilizar o "LuckPerms" para fazer um trabalho melhor.
# Qualquer dúvida ou problemas com o plugin entre em contato pelo discord fixado acima.

# Permissão para setar cargo: ( astral.cmd.setgroup )
# {target} > jogador alvo.
# {group} > grupo setado.

# =======================================================



mensagens:
  # Mensagens de êxito.
  sucess:
    grupo-setado: "&aGrupo: {group}, setado com sucesso!"
    grupo-alterado: "&aVocê alterou o grupo de {target} para {group}."
    grupo-kick: "&5&lASTRAL PLUGINS\n\n&7   Você teve seu grupo alterado para &e&n&l{group}.\n\n&7     Agora basta relogar e desfrutar da sua nova tag! \n \n&a&l= )"

  # Mensagens de falha.
  error:
    jogador-nao-encontrado: "&cO jogador informado não foi encontrado."
    grupo-nao-encontrado: "&cO grupo selecionado não foi encontrado."
    grupo-nao-informado: "&cInforme um grupo para setar no jogador."
    sem-permissao: "&cVocê não possui permissão para fazer isso."

config:
  # Ativar e desativar sistema para expulsar o jogador automaticamente ao setar grupo.
  ativar-kick: true

  # Ativar e desativar som após setar um grupo no jogador será emitido um som (som do ender-dragon).
  ativar-sound: true

  # Ativar e desativar titulos após setar um grupo no jogador.
  ativar-titulos: true

  # Títulos
  title-grupo: "&c{target}"
  subtitle-grupo: "&fTornou-se {group}&f!"

  # Comando a ser executado para setar o grupo do jogador (LuckPerms...)
  command: "lp user {target} parent set {group}"

  # Lista de grupos ativos. Todos os grupos registrados aqui devem ser os mesmos do seu sistema de permissão.
  # Você pode adicionar ou remover.
  grupos-ativos:
    - master
    - gerente
    - admin
    - moderador
    - ajudante
    - yt
    - mvpplus
    - mvp
    - vip
    - default