name: AstralTags
version: 1.0
author: Laas
description: Plugin de gerênciamento de grupos desenvolvido pela Astral Plugins.

main: dev.astralplugins.laas.tags.Main
commands:
  setgroup:
    aliases:
      - setargrupo